//------------------------------------------------------------------------------
//--  <autogenerated>
//--      This code was generated by a tool.
//--      Changes to this file may cause incorrect behavior and will be lost if
//--      the code is regenerated.
//--  </autogenerated>
//------------------------------------------------------------------------------

using Joy.MVVM;
using Joy.MVVM.DataBinding;
using UnityEngine;
using UnityEngine.UI;

[ViewSettingAttribute("Assets/Art/UI/Prefab/Common/LoadingPage.prefab")]
public class LoadingPageGenerate : Window
{
	public GameObject _LSclListView;
	public Slider _SldBar;
	public Text _TxtNum;
	public Text _TxtSpeed;
	public ScrollRect _SclListView;
	public GameObject _SclListViewContent;
	public GameObject _SclListViewTemplate;
	public IListView _ListView;
	public Button _BtnIcon;
	public Text _TxtName;
	public Image _ImgIcon;
	public Transform _BGObj;

	protected override void OnGenerate()
	{
		_LSclListView = transform.Find("_LSclListView").gameObject;
		_SldBar = transform.Find("_SldBar").GetComponent<Slider>();
		_TxtNum = transform.Find("_SldBar/_TxtNum").GetComponent<Text>();
		_TxtSpeed = transform.Find("_TxtSpeed").GetComponent<Text>();
		_SclListView = transform.Find("_SclListView").GetComponent<ScrollRect>();
		_SclListViewContent = _SclListView.transform.Find("Content").gameObject;
		_SclListViewTemplate = _SclListView.transform.Find("Template").gameObject;
		_ListView = CreateListView();
		_ListView.Template = _SclListViewTemplate;
		_ListView.Content = _SclListViewContent;
		_ListView.Scroll = _SclListView;
		_ListView.Parent = this;
		_BtnIcon = transform.Find("_LSclListView/Template/_BtnIcon").GetComponent<Button>();
		_TxtName = transform.Find("_LSclListView/Template/_TxtName").GetComponent<Text>();
		_ImgIcon = transform.Find("_LSclListView/Template/_ImgIcon").GetComponent<Image>();
		_BGObj = transform.Find("_BGObj");
	}

	protected void BindViewModel(BindingSet bindSet, LoadingPageViewModelGenerate vm)
	{
		bindSet.Bind(vm).For(() => vm.SldBar, nameof(vm.SldBar)).To(Refresh_SldBar);
		bindSet.Bind(vm).For(() => vm.TxtNum, nameof(vm.TxtNum)).To(Refresh_TxtNum);
		bindSet.Bind(vm).For(() => vm.TxtSpeed, nameof(vm.TxtSpeed)).To(Refresh_TxtSpeed);
		bindSet.BindList(vm).For(() => vm.ListView, nameof(vm.ListView)).To(_ListView);
		bindSet.BindButton(_BtnIcon).For(_BtnIcon.onClick).To(vm.OnClickIcon);
		bindSet.Bind(vm).For(() => vm.TxtName, nameof(vm.TxtName)).To(Refresh_TxtName);
		bindSet.Bind(vm).For(() => vm.ImgIcon, nameof(vm.ImgIcon)).To(Refresh_ImgIcon);
	}

	protected virtual void Refresh_SldBar(float value)
	{
		_SldBar.value = value;
	}

	protected virtual void Refresh_TxtNum(string value)
	{
		_TxtNum.text = value;
	}

	protected virtual void Refresh_TxtSpeed(string value)
	{
		_TxtSpeed.text = value;
	}

	protected virtual IListView CreateListView()
	{
		return AddSubView<ListView<ItemLoadingPageListViewGenerate>>(_SclListView.gameObject);
	}

	protected virtual void Refresh_TxtName(string value)
	{
		_TxtName.text = value;
	}

	protected virtual void Refresh_ImgIcon(Sprite value)
	{
		_ImgIcon.sprite = value;
	}

}

public class LoadingPageViewModelGenerate : ViewModel
{
	float _SldBar;
	public float SldBar
	{
		get { return _SldBar; }
		set { Set(ref _SldBar, value); }
	}
	string _TxtNum;
	public string TxtNum
	{
		get { return _TxtNum; }
		set { Set(ref _TxtNum, value); }
	}
	string _TxtSpeed;
	public string TxtSpeed
	{
		get { return _TxtSpeed; }
		set { Set(ref _TxtSpeed, value); }
	}
	ObservableList<ItemLoadingPageListViewViewModelGenerate> _ListView = new ObservableList<ItemLoadingPageListViewViewModelGenerate>();
	public ObservableList<ItemLoadingPageListViewViewModelGenerate> ListView
	{
		get { return _ListView; }
		set { Set(ref _ListView, value); }
	}
	public virtual void OnClickIcon() { Joy.Debug.Log("click _BtnIcon"); }
	string _TxtName;
	public string TxtName
	{
		get { return _TxtName; }
		set { Set(ref _TxtName, value); }
	}
	Sprite _ImgIcon;
	public Sprite ImgIcon
	{
		get { return _ImgIcon; }
		set { Set(ref _ImgIcon, value); }
	}
}

public class ItemLoadingPageListViewGenerate : ItemView
{
	public Button _BtnIcon;
	public Text _TxtName;
	public Image _ImgIcon;

	protected override void OnGenerate()
	{
		_BtnIcon = transform.Find("_BtnIcon").GetComponent<Button>();
		_TxtName = transform.Find("_TxtName").GetComponent<Text>();
		_ImgIcon = transform.Find("_ImgIcon").GetComponent<Image>();
	}

	protected override void ReplaceViewModel(ViewModel model)
	{
		BindViewModel(bindSet, model);
	}

	protected void BindViewModel(BindingSet bindSet, ViewModel model)
	{
		var vm = model as ItemLoadingPageListViewViewModelGenerate;
		bindSet.BindButton(_BtnIcon).For(_BtnIcon.onClick).To(vm.OnClickIcon);
		bindSet.Bind(vm).For(() => vm.TxtName, nameof(vm.TxtName)).To(Refresh_TxtName);
		bindSet.Bind(vm).For(() => vm.ImgIcon, nameof(vm.ImgIcon)).To(Refresh_ImgIcon);
	}

	protected virtual void Refresh_TxtName(string value)
	{
		_TxtName.text = value;
	}

	protected virtual void Refresh_ImgIcon(Sprite value)
	{
		_ImgIcon.sprite = value;
	}

}

public class ItemLoadingPageListViewViewModelGenerate : ViewModel
{
	public virtual void OnClickIcon() { Joy.Debug.Log("click _BtnIcon"); }
	string _TxtName;
	public string TxtName
	{
		get { return _TxtName; }
		set { Set(ref _TxtName, value); }
	}
	Sprite _ImgIcon;
	public Sprite ImgIcon
	{
		get { return _ImgIcon; }
		set { Set(ref _ImgIcon, value); }
	}
}

